// <auto-generated />
namespace Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addjobexpiry2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjobexpiry2));
        
        string IMigrationMetadata.Id
        {
            get { return "202211031537465_addjobexpiry2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
