//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abd El-hafiz.
        /// </summary>
        internal static string AbdElhafiz {
            get {
                return ResourceManager.GetString("AbdElhafiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG aspires to leave a print in the management consulting and development . working with companies as well as individuals , establishing partnerships , enabling SMG of becoming a well reowned name that symbolizes quality and master..
        /// </summary>
        internal static string AboutSMG_Desc_1 {
            get {
                return ResourceManager.GetString("AboutSMG_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dream that began in 2013 . Under the blessings of almighty god and with the hands of SMG calibers, it became a reality. With headquarters in cairo,Egypt, SMG consulting and Training Fields, was established in 2021. Despite a timely gab between the dream formation formation and the initial steps of implementation, Our will to proceed launched the product into a reality.
        /// </summary>
        internal static string AboutSMG_Desc_2 {
            get {
                return ResourceManager.GetString("AboutSMG_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to through a reliance on Allah and via our personnel , all resources were dedicated to orchestrate authentic ideas out of the box. That in turn would allow us to achieve the outmost benefit for our success parteners, convoyed in the cost minimizing and profit maximization. In addition to maintaining a workforce that is being provided with topnotch training programs. Updated with the last theoretical and practical implementatios on an international scale, intended for the human captal development..
        /// </summary>
        internal static string AboutSMG_Desc_3 {
            get {
                return ResourceManager.GetString("AboutSMG_Desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SMG.
        /// </summary>
        internal static string AboutSMG_Title {
            get {
                return ResourceManager.GetString("AboutSMG_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Officer.
        /// </summary>
        internal static string AdminOfficer {
            get {
                return ResourceManager.GetString("AdminOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahmed Mahmoud.
        /// </summary>
        internal static string AhmedMahmoud {
            get {
                return ResourceManager.GetString("AhmedMahmoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for job.
        /// </summary>
        internal static string Applyforjob {
            get {
                return ResourceManager.GetString("Applyforjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayman Saad.
        /// </summary>
        internal static string AymanSaad {
            get {
                return ResourceManager.GetString("AymanSaad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Developer.
        /// </summary>
        internal static string BusinessDeveloper {
            get {
                return ResourceManager.GetString("BusinessDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        internal static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE IN SMG BELIEVE THAT WE WILL BE A MARKET LEADERS IN OUR INDUSTRY, SO THANKS FOR MY GOLDEN TEAM FOR THEIR PASSION TO START THIS DREAM TO BECOME ONE OF THE BIGGEST CONSULTANCIES &amp; TRAINING FIRM IN LINE TO BE PART OF EGYPT 3030 VISION UNDER THE SLOGAN.
        /// </summary>
        internal static string CEOMessage_Desc_1 {
            get {
                return ResourceManager.GetString("CEOMessage_Desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (COMPREHENSIVE SUSTAINABLE DEVELOPMENT).
        /// </summary>
        internal static string CEOMEssage_Desc_2 {
            get {
                return ResourceManager.GetString("CEOMEssage_Desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO Message.
        /// </summary>
        internal static string CEOMessage_Title {
            get {
                return ResourceManager.GetString("CEOMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COO.
        /// </summary>
        internal static string COO {
            get {
                return ResourceManager.GetString("COO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses galleries.
        /// </summary>
        internal static string CoursesGallerries {
            get {
                return ResourceManager.GetString("CoursesGallerries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doha Shaker.
        /// </summary>
        internal static string DohaShaker {
            get {
                return ResourceManager.GetString("DohaShaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flutter Developer.
        /// </summary>
        internal static string FlutterDeveloper {
            get {
                return ResourceManager.GetString("FlutterDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for applying.
        /// </summary>
        internal static string ForApplying {
            get {
                return ResourceManager.GetString("ForApplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For registeration.
        /// </summary>
        internal static string ForRegisteration {
            get {
                return ResourceManager.GetString("ForRegisteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        internal static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headquarters.
        /// </summary>
        internal static string Headquarters {
            get {
                return ResourceManager.GetString("Headquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hossam Nagy.
        /// </summary>
        internal static string HossamNagy {
            get {
                return ResourceManager.GetString("HossamNagy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Find Us.
        /// </summary>
        internal static string HowToFindUs {
            get {
                return ResourceManager.GetString("HowToFindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, just fill in the contact form, and we will answer you shortly..
        /// </summary>
        internal static string HowToFindUs_Desc {
            get {
                return ResourceManager.GetString("HowToFindUs_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resource.
        /// </summary>
        internal static string HumanResource {
            get {
                return ResourceManager.GetString("HumanResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string InvertLang {
            get {
                return ResourceManager.GetString("InvertLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        internal static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job is not available now.
        /// </summary>
        internal static string JobNotAvailable {
            get {
                return ResourceManager.GetString("JobNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        internal static string Lectures {
            get {
                return ResourceManager.GetString("Lectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 Ibrahim Ibn El Mahdi st, Nasr City, Cairo Egypt.
        /// </summary>
        internal static string L_Address {
            get {
                return ResourceManager.GetString("L_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 Ibrahim Ibn El Mahdi st,.
        /// </summary>
        internal static string L_Address_1 {
            get {
                return ResourceManager.GetString("L_Address_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasr City, Cairo Egypt.
        /// </summary>
        internal static string L_Address_2 {
            get {
                return ResourceManager.GetString("L_Address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        internal static string L_AllRightsReserved {
            get {
                return ResourceManager.GetString("L_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string L_FollowUs {
            get {
                return ResourceManager.GetString("L_FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG Is not just a company, it is your partner to improve your career &amp; supply you anywhere at any time..
        /// </summary>
        internal static string L_Hint_Desc {
            get {
                return ResourceManager.GetString("L_Hint_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together, we can enable your business to achieve even more..
        /// </summary>
        internal static string L_Hint_Title {
            get {
                return ResourceManager.GetString("L_Hint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        internal static string L_LatestNews {
            get {
                return ResourceManager.GetString("L_LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Our Team.
        /// </summary>
        internal static string L_MeetOurTeam {
            get {
                return ResourceManager.GetString("L_MeetOurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string L_Menu_AboutUs {
            get {
                return ResourceManager.GetString("L_Menu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        internal static string L_Menu_Careers {
            get {
                return ResourceManager.GetString("L_Menu_Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string L_Menu_ContactUs {
            get {
                return ResourceManager.GetString("L_Menu_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string L_Menu_Courses {
            get {
                return ResourceManager.GetString("L_Menu_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string L_Menu_Gallery {
            get {
                return ResourceManager.GetString("L_Menu_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string L_Menu_Home {
            get {
                return ResourceManager.GetString("L_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seminars.
        /// </summary>
        internal static string L_Menu_Seminars {
            get {
                return ResourceManager.GetString("L_Menu_Seminars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string L_Menu_Services {
            get {
                return ResourceManager.GetString("L_Menu_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goals.
        /// </summary>
        internal static string L_OurGoal {
            get {
                return ResourceManager.GetString("L_OurGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping companies to reach the optimum status in operation to maximize profits and decrease costs by providing external sources of conjoined services with uniform quality..
        /// </summary>
        internal static string L_OurGoal_1_Desc {
            get {
                return ResourceManager.GetString("L_OurGoal_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimum status for companies.
        /// </summary>
        internal static string L_OurGoal_1_Title {
            get {
                return ResourceManager.GetString("L_OurGoal_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly and indirectly influence in the feild of management consulting..
        /// </summary>
        internal static string L_OurGoal_2_Desc {
            get {
                return ResourceManager.GetString("L_OurGoal_2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management consulting.
        /// </summary>
        internal static string L_OurGoal_2_Title {
            get {
                return ResourceManager.GetString("L_OurGoal_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be pioneers in our field in order to transfer our experience to our experience in success..
        /// </summary>
        internal static string L_OurGoal_3_Desc {
            get {
                return ResourceManager.GetString("L_OurGoal_3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer our experience.
        /// </summary>
        internal static string L_OurGoal_3_Title {
            get {
                return ResourceManager.GetString("L_OurGoal_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributing to escalating a new generation of conscious youth to serve ourbeloved country , Egypt..
        /// </summary>
        internal static string L_OurGoal_4_Desc {
            get {
                return ResourceManager.GetString("L_OurGoal_4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalating a new generation.
        /// </summary>
        internal static string L_OurGoal_4_Title {
            get {
                return ResourceManager.GetString("L_OurGoal_4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        internal static string L_OurMission {
            get {
                return ResourceManager.GetString("L_OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our success partners.
        /// </summary>
        internal static string L_OurPartners {
            get {
                return ResourceManager.GetString("L_OurPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Principles.
        /// </summary>
        internal static string L_OurPrinciples {
            get {
                return ResourceManager.GetString("L_OurPrinciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We firmly believe that in the field of corporate, there is noone size-fits-all scale..
        /// </summary>
        internal static string L_OurPrinciples_1 {
            get {
                return ResourceManager.GetString("L_OurPrinciples_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therefore, SMG seeks to be one of the leading companies in its field by providing the best smart and professional solutions that enables organizations to build, manage and develop their resource strategies in line with the latest standards..
        /// </summary>
        internal static string L_OurPrinciples_2 {
            get {
                return ResourceManager.GetString("L_OurPrinciples_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        internal static string L_OurServices {
            get {
                return ResourceManager.GetString("L_OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide comprehensive services in many fields that is very important to each company..
        /// </summary>
        internal static string L_OurServices_1_Desc {
            get {
                return ResourceManager.GetString("L_OurServices_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development.
        /// </summary>
        internal static string L_OurServices_1_Title {
            get {
                return ResourceManager.GetString("L_OurServices_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help companies with a software consultancy that
        ///equips busoness with the latest software technology / IT solutions..
        /// </summary>
        internal static string L_OurServices_2_Desc {
            get {
                return ResourceManager.GetString("L_OurServices_2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business consulting.
        /// </summary>
        internal static string L_OurServices_2_Title {
            get {
                return ResourceManager.GetString("L_OurServices_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG offers the comprehensive range of services that any company would expect from an HR outsourcing firm..
        /// </summary>
        internal static string L_OurServices_3_Desc {
            get {
                return ResourceManager.GetString("L_OurServices_3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human capital management.
        /// </summary>
        internal static string L_OurServices_3_Title {
            get {
                return ResourceManager.GetString("L_OurServices_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We deliver training and knowledge transfer based on the learning needs and awareness levels..
        /// </summary>
        internal static string L_OurServices_4_Desc {
            get {
                return ResourceManager.GetString("L_OurServices_4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training &amp; development.
        /// </summary>
        internal static string L_OurServices_4_Title {
            get {
                return ResourceManager.GetString("L_OurServices_4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        internal static string L_QuickLinks {
            get {
                return ResourceManager.GetString("L_QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        internal static string L_SMG {
            get {
                return ResourceManager.GetString("L_SMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG For Consultancy &amp; Training Solutions -.
        /// </summary>
        internal static string L_Title {
            get {
                return ResourceManager.GetString("L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Clients Choose Us.
        /// </summary>
        internal static string L_WhyClientsChooseUs {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We work in an atmosphere of trust and camaraderie, where partners help each other..
        /// </summary>
        internal static string L_WhyClientsChooseUs_1_Desc {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competent Professionals.
        /// </summary>
        internal static string L_WhyClientsChooseUs_1_Title {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are committed to providing clients with the best value and service in the industry..
        /// </summary>
        internal static string L_WhyClientsChooseUs_2_Desc {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs_2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior Service.
        /// </summary>
        internal static string L_WhyClientsChooseUs_2_Title {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing value through straightforward commissions and added services..
        /// </summary>
        internal static string L_WhyClientsChooseUs_3_Desc {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs_3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitive Pricing.
        /// </summary>
        internal static string L_WhyClientsChooseUs_3_Title {
            get {
                return ResourceManager.GetString("L_WhyClientsChooseUs_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahmoud El-Ansary.
        /// </summary>
        internal static string MahmoudAnasary {
            get {
                return ResourceManager.GetString("MahmoudAnasary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr Amr Wagih.
        /// </summary>
        internal static string MrAmrWagih {
            get {
                return ResourceManager.GetString("MrAmrWagih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opening vacancies available now.
        /// </summary>
        internal static string NoOpeningVacations {
            get {
                return ResourceManager.GetString("NoOpeningVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG is an expert house specialized in consulting and supplies , Therefore it is focusing on Business consulting and Human capital management.
        /// </summary>
        internal static string Ourvalue_Desc {
            get {
                return ResourceManager.GetString("Ourvalue_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibility.
        /// </summary>
        internal static string Ourvalue_Item_1 {
            get {
                return ResourceManager.GetString("Ourvalue_Item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credibility.
        /// </summary>
        internal static string Ourvalue_Item_2 {
            get {
                return ResourceManager.GetString("Ourvalue_Item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Ourvalue_Item_3 {
            get {
                return ResourceManager.GetString("Ourvalue_Item_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Ourvalue_Item_4 {
            get {
                return ResourceManager.GetString("Ourvalue_Item_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tansparancy.
        /// </summary>
        internal static string Ourvalue_Item_5 {
            get {
                return ResourceManager.GetString("Ourvalue_Item_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string Ourvalue_Item_6 {
            get {
                return ResourceManager.GetString("Ourvalue_Item_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our value.
        /// </summary>
        internal static string Ourvalue_Title {
            get {
                return ResourceManager.GetString("Ourvalue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passant Mostafa.
        /// </summary>
        internal static string PassantMostafa {
            get {
                return ResourceManager.GetString("PassantMostafa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rawan Osama.
        /// </summary>
        internal static string RawanOsama {
            get {
                return ResourceManager.GetString("RawanOsama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register For.
        /// </summary>
        internal static string RegisterFor {
            get {
                return ResourceManager.GetString("RegisterFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        internal static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seminars galleries.
        /// </summary>
        internal static string SeminarsGallerries {
            get {
                return ResourceManager.GetString("SeminarsGallerries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Overview.
        /// </summary>
        internal static string ServicesOverview {
            get {
                return ResourceManager.GetString("ServicesOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide comprehensive services in many fields that is very important to each company..
        /// </summary>
        internal static string Services_Desc {
            get {
                return ResourceManager.GetString("Services_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        internal static string Socialmedia {
            get {
                return ResourceManager.GetString("Socialmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;p class=&quot;text-gray-05&quot;&gt;We work hard to create, execute and deliver high-quality advisory and management services. As well as providing you with the tools you need to improve your processes and management structure, boost customer happiness and add value to your company.&lt;/p&gt;
        ///                    &lt;p class=&quot;text-gray-05&quot;&gt;We assist you in building and managing sound management systemsthat comply with international standards. As well as re-viewing and re-engineering existing processes to improve and optimize cu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_Services_1_Desc {
            get {
                return ResourceManager.GetString("S_Services_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;p class=&quot;text-gray-05&quot;&gt;SMG offers the comprehensive range of services that any company would expect from an HR outsourcing firm.&lt;/p&gt;
        ///                    &lt;p class=&quot;text-gray-05&quot;&gt;The outsourcing includes the follwing :&lt;/p&gt;
        ///                    &lt;ul class=&quot;list-marked&quot;&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Personnel &amp;amp; Payroll audit&lt;/li&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Payroll management system&lt;/li&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Organizational struct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_Services_2_Desc {
            get {
                return ResourceManager.GetString("S_Services_2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;p class=&quot;text-gray-05&quot;&gt;Our highly qualified trainers help individuals and companies to learn and improve their qualifications to compete in the market.&lt;/p&gt;
        ///                    &lt;p class=&quot;text-gray-05&quot;&gt;We deliver training and knowledge transfer based on the learning needs and awareness levels.&lt;/p&gt;
        ///                    &lt;ul class=&quot;list-marked&quot;&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Excel for HR&lt;/li&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Professional human resource course&lt;/li&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_Services_3_Desc {
            get {
                return ResourceManager.GetString("S_Services_3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;text-gray-05&quot;&gt;We help companies with a software development consultancy that equips businesses with the latest software technology / IT solutions to add  real value with a reasonable price , such as :&lt;/p&gt;
        ///                    &lt;ul class=&quot;list-marked&quot;&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;ERP system&lt;/li&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Website&lt;/li&gt;
        ///                        &lt;li style=&quot;font-size:12px&quot;&gt;Mobile applications&lt;/li&gt;
        ///                    &lt;/ul&gt;.
        /// </summary>
        internal static string S_Services_4_Desc {
            get {
                return ResourceManager.GetString("S_Services_4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course is approved by : .
        /// </summary>
        internal static string ThisCourseApprovedBy {
            get {
                return ResourceManager.GetString("ThisCourseApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your CV.
        /// </summary>
        internal static string UploadyourCV {
            get {
                return ResourceManager.GetString("UploadyourCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice CEO.
        /// </summary>
        internal static string ViceCEO {
            get {
                return ResourceManager.GetString("ViceCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will contact you as soon as possible.
        /// </summary>
        internal static string WeWillContactasap {
            get {
                return ResourceManager.GetString("WeWillContactasap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp mobile.
        /// </summary>
        internal static string WhatsappMobile {
            get {
                return ResourceManager.GetString("WhatsappMobile", resourceCulture);
            }
        }
    }
}
